language: node_js
node_js:
  - '12'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=3000
    - MONGODB_URL=mongodb://toanplq:061191@cluster0-shard-00-00.z15fs.mongodb.net:27017,cluster0-shard-00-01.z15fs.mongodb.net:27017,cluster0-shard-00-02.z15fs.mongodb.net:27017/Cluster0?ssl=true&replicaSet=atlas-co08ew-shard-0&authSource=admin&retryWrites=true&w=majority
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
