version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      MONGODB_URL: mongodb://root:admin@mongodb
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      SMTP_HOST: email-server
      SMTP_PORT: 587
      SMTP_USERNAME: email-server-username
      SMTP_PASSWORD: email-server-password
      EMAIL_FROM: support@yourapp.com
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.17-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongodb
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
