version: '3'

services:
  node-app:
    build: .
    image: node-app
    depends_on:
      - "postgres"
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    env_file:
      - .env

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypostgres
      PGDATA: /data/postgres
      POSTGRES_DB: mydb
    volumes:
       - dbdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - node-network
    restart: unless-stopped

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
